// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL_h4iGsVKuUwKj9wi6pBRRJ0W2RTmyRY',
    appId: '1:705339786160:web:5fd4da8f60e2466c088c75',
    messagingSenderId: '705339786160',
    projectId: 'weather-app-bc3dd',
    authDomain: 'weather-app-bc3dd.firebaseapp.com',
    storageBucket: 'weather-app-bc3dd.appspot.com',
    measurementId: 'G-6F5M47CPGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgW0iS7l2ELAhhvdjpfEPw-QtVkJqrfNw',
    appId: '1:705339786160:android:559c5d987746e79c088c75',
    messagingSenderId: '705339786160',
    projectId: 'weather-app-bc3dd',
    storageBucket: 'weather-app-bc3dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJR_AP6DW2XoiMxufKKqzg19aP6vBGwss',
    appId: '1:705339786160:ios:14b2056a539e92e3088c75',
    messagingSenderId: '705339786160',
    projectId: 'weather-app-bc3dd',
    storageBucket: 'weather-app-bc3dd.appspot.com',
    iosClientId: '705339786160-959c0aikggm5okbgmsl1p13ej9uulkc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJR_AP6DW2XoiMxufKKqzg19aP6vBGwss',
    appId: '1:705339786160:ios:53deedf94e0eedf2088c75',
    messagingSenderId: '705339786160',
    projectId: 'weather-app-bc3dd',
    storageBucket: 'weather-app-bc3dd.appspot.com',
    iosClientId: '705339786160-745nnlgbk1a3ci8d31it07vtraar9er1.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloApp.RunnerTests',
  );
}
